# This is a basic workflow to compile the main.tex file and push the pdf into the repository
name: Compile Latex Document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch and pdf file are ignored
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.pdf'
    
#  pull_request:
#    branches: [ "main" ]
#    paths-ignore:
#      - '*.pdf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
      - name: Publish LaTeX
        run : |
          git config --global user.email "fs-it@physik.rub.de"
          git config --global user.name "J.A.R.V.I.S."
          git add -f *.pdf
          git commit -m "[J.A.R.V.I.S.] Update PDF"
          git push